<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Version information for local_aiquizgenerator.
 *
 * @package    local_aiquizgenerator
 * @copyright  2026 Renat Furs <fursrenat@gmail.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
namespace local_aiquizgenerator;

defined('MOODLE_INTERNAL') || die();

/**
 * Class responsible for converting JSON to Moodle XML
 */
class format_converter {
    /**
     * Converts JSON generated by LLM into Moodle XML
     *
     * @param string $jsoncontent Clean JSON.
     * @return string Generated XML content.
     * @throws \moodle_exception
     */
    public function convert_json_to_xml(string $jsoncontent): string {
        $data = json_decode($jsoncontent, true);
        if (!$data || !isset($data['questions'])) {
            throw new \moodle_exception('invalidjsonresponse', 'local_aiquizgenerator');
        }

        $dom = new \DOMDocument('1.0', 'UTF-8');
        $dom->formatOutput = true;
        $quiz = $dom->createElement('quiz');
        $dom->appendChild($quiz);

        foreach ($data['questions'] as $q) {
            $question = $dom->createElement('question');
            $question->setAttribute('type', $q['questiontype']);

            $name = $dom->createElement('name');
            $name->appendChild($dom->createElement('text', htmlspecialchars($q['name'])));
            $question->appendChild($name);

            $qtext = $q['questiontext'];
            if (!empty($q['code'])) {
                $qtext .= '<br><br><pre><code>' . htmlspecialchars($q['code']) . '</code></pre>';
            }

            $questiontext = $dom->createElement('questiontext');
            $questiontext->setAttribute('format', 'html');
            $textnode = $dom->createElement('text');
            $textnode->appendChild($dom->createCDATASection($qtext));
            $questiontext->appendChild($textnode);
            $question->appendChild($questiontext);

            $question->appendChild($dom->createElement('generalfeedback', ''));
            $question->appendChild($dom->createElement('defaultgrade', '1.0000000'));
            $question->appendChild($dom->createElement('penalty', '0.3333333'));
            $question->appendChild($dom->createElement('hidden', '0'));
            $question->appendChild($dom->createElement('idnumber', ''));

            if ($q['questiontype'] === 'multichoice') {
                $correctanswers = 0;
                foreach ($q['answers'] as $ans) {
                    if ((float)$ans['fraction'] > 0) {
                        $correctanswers++;
                    }
                }

                $single = ($correctanswers <= 1) ? 'true' : 'false';
                $question->appendChild($dom->createElement('single', $single));
                $question->appendChild($dom->createElement('shuffleanswers', '1'));
                $question->appendChild($dom->createElement('answernumbering', 'abc'));
                $question->appendChild($dom->createElement('showstandardinstruction', '0'));
            }

            foreach ($q['answers'] as $ans) {
                $answer = $dom->createElement('answer');
                $answer->setAttribute('fraction', $ans['fraction']);
                $answer->setAttribute('format', 'html');

                $anstext = $dom->createElement('text');
                $anstext->appendChild($dom->createCDATASection($ans['text']));
                $answer->appendChild($anstext);

                $feedback = $dom->createElement('feedback');
                $feedback->setAttribute('format', 'html');
                $feedback->appendChild($dom->createElement('text', ''));
                $answer->appendChild($feedback);

                $question->appendChild($answer);
            }

            if ($q['questiontype'] === 'essay') {
                $question->appendChild($dom->createElement('responseformat', 'editor'));
                $question->appendChild($dom->createElement('responserequired', '1'));
                $question->appendChild($dom->createElement('responsefieldlines', '15'));
                $question->appendChild($dom->createElement('attachments', '0'));
            }

            $quiz->appendChild($question);
        }
        return $dom->saveXML();
    }
}
